import { reactive } from "vue"

let task_list = reactive({
    stage0: {
        task1: {
            code_name: "task1",
            stage: "stage0",
            name: 'Подготовить презентацию стартапа',
            type: 'major',
            desc: 'Вам необходимо подготовить презентацию вашего стартап-проекта, чтобы найти партнеров и привлекать инвестиции. ИСПОЛНИТЕЛИ: CEO 1 уровня.',
            time: 1,
            progress: 0,
            additional_expenses: 1000,
            is_performed: true,
            required_roles: [
                "ceo1",
            ],
            assigned_employees: {
                ceo1: "null",
            },
            complexity: {
                num: 1,
                text: "Гипер легкая",
            },
            reward: {
                type: "none",
                amount: 0,
            },
            id: 0,
            active: false,
        },
        task2: {
            code_name: "task2",
            stage: "stage0",
            name: 'Привлечь первые инвестиции FFF',
            type: 'major',
            desc: 'Не секрет, что ключевой источник стартовых инвестиций — так называемые FFF-money. Это деньги, получаемые фаундерами от друзей, семьи и рискованных знакомых (Friends, Family & Fools). Инвестиции нужны для найма сотрудников, оплаты аренды и других расходов. ИСПОЛНИТЕЛИ: CEO 1 уровня. НАГРАДА: Получите первую инвестиции в размере — (ПЛОХО < ХОРОШО: 200 000 рублей < ОТЛИЧНО) зависит от УСПЕШНОСТИ выполнения задачи за 5% доли компании.',
            time: 1,
            progress: 0,
            additional_expenses: 1000,
            is_performed: true,
            required_roles: [
                "ceo1",
            ],
            assigned_employees: {
                ceo1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "investments",
                amount: 200000,
                share_change: 5,
            },
            id: 1,
            active: false,
        },
    },
    stage1: {
        task3: {
            code_name: "task3",
            stage: "stage1",
            name: 'Разработать фирменный стиль',
            type: 'major',
            desc: 'Брендинг поможет завоевать доверие аудитории, и сделать продукт компании узнаваемым и веделиться среди конкурентов. Соответственно повыситься репутация компании и доверие, которое будет влять на рост капитализации компании. ИСПОЛНИТЕЛИ: CEO 1 уровня / Маркетолог 1 уровня / Дизайнер 1 уровня. НАГРАДА: Рост капитализации компании на — (ПЛОХО < ХОРОШО: 300 000 рублей < ОТЛИЧНО) зависит от УСПЕШНОСТИ выполнения задачи.',
            time: 2,
            progress: 0,
            additional_expenses: 7500,
            is_performed: true,
            required_roles: [
                "ceo1",
                "marketer1",
                "designer1",
            ],
            assigned_employees: {
                ceo1: "null",
                marketer1: "null",
                designer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "capitilize",
                amount: 300000,
            },
            id: 2,
            active: false,
        },
        task4: {
            code_name: "task4",
            stage: "stage1",
            name: 'Отправить заявку на участие в Акселераторе В69 и привлечь Pre-Seed инвестиции',
            type: 'major',
            desc: 'описание задания 1',
            time: 3,
            progress: 0,
            additional_expenses: 4000,
            is_performed: true,
            required_roles: [
                "ceo1",
                "marketer1",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                ceo1: "null",
                marketer1: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 40000000,
                share_change: 5,
            },
            id: 3,
            active: false,
        },
        task5: {
            code_name: "task5",
            stage: "stage1",
            name: 'Разработать бизнес-модель',
            type: 'major',
            desc: 'описание задания 1',
            time: 2,
            progress: 0,
            additional_expenses: 5000,
            is_performed: true,
            required_roles: [
                "ceo1",
                "marketer1",
            ],
            assigned_employees: {
                ceo1: "null",
                marketer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "capitilize",
                amount: 5000000,
            },
            id: 4,
            active: false,
        },
        task6: {
            code_name: "task6",
            stage: "stage1",
            name: 'Провести глубинное интервью',
            type: 'major',
            desc: 'описание задания 1',
            time: 3,
            progress: 0,
            additional_expenses: 10000,
            is_performed: true,
            required_roles: [
                "ceo1",
                "marketer1",
            ],
            assigned_employees: {
                ceo1: "null",
                marketer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "capitilize",
                amount: 3000000,
            },
            id: 5,
            active: false,
        },
        task7: {
            code_name: "task7",
            stage: "stage1",
            name: 'Разработать сайт на заказ',
            type: 'minor',
            desc: 'описание задания 1',
            time: 2,
            progress: 0,
            additional_expenses: 10000,
            is_performed: true,
            required_roles: [
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "income",
                amount: 800000,
            },
            id: 6,
            active: false,
        },
    },
    stage2: {
        task8: {
            code_name: "task8",
            stage: "stage2",
            name: 'Разработать MVP',
            type: 'major',
            desc: 'Описание задания 8',
            time: 5,
            progress: 0,
            additional_expenses: 20000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer1",
                "designer1",
                "developer2",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer1: "null",
                designer1: "null",
                developer2: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: 10000000,
            },
            id: 7,
            active: false,
        },
        task9: {
            code_name: "task9",
            stage: "stage2",
            name: 'Привлечь Seed инвестиции у Фонда посевных инвестиций',
            type: 'major',
            desc: 'Описание задания 9',
            time: 5,
            progress: 0,
            additional_expenses: 10000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer2",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer2: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: "Вычисляется по формуле",
                share_change: 10,
            },
            id: 8,
            active: false,
        },
        task10: {
            code_name: "task10",
            stage: "stage2",
            name: 'Разработать мобильное приложение',
            type: 'minor',
            desc: 'Описание задания 10',
            time: 2,
            progress: 0,
            additional_expenses: 40000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer1",
                "designer1",
                "developer2",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer1: "null",
                designer1: "null",
                developer2: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 1000000,
            },
            id: 9,
            active: false,
        },
        task11: {
            code_name: "task11",
            stage: "stage2",
            name: 'Устроить корпоратив и отметить день рождения',
            type: 'minor',
            desc: 'Описание задания 11',
            time: 1,
            progress: 0,
            additional_expenses: 150000,
            is_performed: true,
            required_roles: [
                "ceo1",
                "marketer1",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                ceo1: "null",
                marketer1: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 2,
                text: "Легкая",
            },
            reward: {
                type: "capitilize",
                amount: 1500000,
            },
            id: 10,
            active: false,
        },
        task12: {
            code_name: "task12",
            stage: "stage2",
            name: 'Разработать мобильное приложение на заказ',
            type: 'minor',
            desc: 'Описание задания 12',
            time: 2,
            progress: 0,
            additional_expenses: 1000,
            is_performed: true,
            required_roles: [
                "marketer1",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                marketer1: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "",
                amount: 1000000,
            },
            id: 11,
            active: false,
        },
    },
    stage3: {
        task13: {
            code_name: "task13",
            stage: "stage3",
            name: 'Разработать стратегию запуска сервиса',
            type: 'major',
            desc: 'Описание задания 13',
            time: 5,
            progress: 0,
            additional_expenses: 60000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer2",
                "marketer1",
                "designer2",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 10000000,
            },
            id: 12,
            active: false,
        },
        task14: {
            code_name: "task14",
            stage: "stage3",
            name: 'Привлечь Ангельские инвестиции у Бизнес-ангела',
            type: 'minor',
            desc: 'Описание задания 14',
            time: 5,
            progress: 0,
            additional_expenses: 10000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer2",
                "designer2",
                "developer2",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer2: "null",
                designer2: "null",
                developer2: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: "Вычисляется по формуле",
                share_change: 15,
            },
            id: 13,
            active: false,
        },
        task15: {
            code_name: "task15",
            stage: "stage3",
            name: 'Привлечь Ангельские инвестиции у Бизнес-демона',
            type: 'minor',
            desc: 'Описание задания 15',
            time: 2,
            progress: 0,
            additional_expenses: 10000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer1",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer1: "null",
            },
            complexity: {
                num: 4,
                text: "Легкая",
            },
            reward: {
                type: "capitilize",
                amount: "Вычисляется по формуле",
                share_change: 25,
            },
            id: 14,
            active: false,
        },
        task16: {
            code_name: "task16",
            stage: "stage3",
            name: 'Запустить промо',
            type: 'major',
            desc: 'Описание задания 16',
            time: 3,
            progress: 0,
            additional_expenses: 400000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer2",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: 20000000,
            },
            id: 15,
            active: false,
        },
        task17: {
            code_name: "task17",
            stage: "stage3",
            name: 'Продать технологию',
            type: 'minor',
            desc: 'Описание задания 17',
            time: 1,
            progress: 0,
            additional_expenses: 1000,
            is_performed: true,
            required_roles: [
                "ceo2",
                "marketer1",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                ceo2: "null",
                marketer1: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "capitilize",
                amount: -1000000,
            },
            id: 16,
            active: false,
        },
    },
    stage4: {
        task18: {
            code_name: "task18",
            stage: "stage4",
            name: 'Активная продажа',
            type: 'major',
            desc: 'Описание задания 18',
            time: 5,
            progress: 0,
            additional_expenses: 100000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 5000000,
            },
            id: 17,
            active: false,
        },
        task19: {
            code_name: "task19",
            stage: "stage4",
            name: 'Запуск интернет-рекламы',
            type: 'major',
            desc: 'Описание задания 19',
            time: 5,
            progress: 0,
            additional_expenses: 400000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer2",
                "designer1",
                "developer1",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
                designer1: "null",
                developer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 5000000,
            },
            id: 18,
            active: false,
        },
        task20: {
            code_name: "task20",
            stage: "stage4",
            name: 'Запуск рекламы в социальных сетях',
            type: 'minor',
            desc: 'Описание задания 20',
            time: 4,
            progress: 0,
            additional_expenses: 300000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer2",
                "designer1",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
                designer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 5000000,
            },
            id: 19,
            active: false,
        },
        task21: {
            code_name: "task21",
            stage: "stage4",
            name: 'Работа с блогерами',
            type: 'minor',
            desc: 'Описание задания 21',
            time: 3,
            progress: 0,
            additional_expenses: 300000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer2",
                "designer1",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
                designer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 1000000,
            },
            id: 20,
            active: false,
        },
        task22: {
            code_name: "task22",
            stage: "stage4",
            name: 'Рекламировать чужие акции своим клиентам',
            type: 'minor',
            desc: 'Описание задания 22',
            time: 1,
            progress: 0,
            additional_expenses: 1000,
            is_performed: true,
            required_roles: [
                "marketer2",
                "marketer1",
            ],
            assigned_employees: {
                marketer2: "null",
                marketer1: "null",
            },
            complexity: {
                num: 4,
                text: "Средняя",
            },
            reward: {
                type: "capitilize",
                amount: -1000000,
            },
            id: 21,
            active: false,
        },
    },
    stage5: {
        task23: {
            code_name: "task23",
            stage: "stage5",
            name: 'Модернизация ИТ-инфраструктуры на отказоустойчивость и безопасность сервиса',
            type: 'major',
            desc: 'Описание задания 23',
            time: 7,
            progress: 0,
            additional_expenses: 1000000,
            is_performed: true,
            required_roles: [
                "developer3",
                "developer2",
                "developer1",
            ],
            assigned_employees: {
                developer3: "null",
                developer2: "null",
                developer1: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: 15000000,
            },
            id: 22,
            active: false,
        },
        task24: {
            code_name: "task24",
            stage: "stage5",
            name: 'Привлечь инвестиции Раунд A у Венчурного фонда',
            type: 'minor',
            desc: 'Описание задания 24',
            time: 5,
            progress: 0,
            additional_expenses: 100000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "designer3",
                "developer3",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                designer3: "null",
                developer3: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: "Вычисляется по формуле",
                share_change: 20,
            },
            id: 23,
            active: false,
        },
        task25: {
            code_name: "task25",
            stage: "stage5",
            name: 'Партнерство с крупным игроком рынка',
            type: 'major',
            desc: 'Описание задания 25',
            time: 5,
            progress: 0,
            additional_expenses: 10000000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer3",
                "developer3",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer3: "null",
                developer3: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: 50000000,
                share_change: 10,
            },
            id: 24,
            active: false,
        },
        task26: {
            code_name: "task26",
            stage: "stage5",
            name: 'Запустить активную маркетинговая кампанию',
            type: 'major',
            desc: 'Описание задания 26',
            time: 5,
            progress: 0,
            additional_expenses: 5000000,
            is_performed: true,
            required_roles: [
                "ceo3",
                "marketer3",
                "marketer2",
                "marketer1",
                "designer2",
                "designer1",
                "developer2",
            ],
            assigned_employees: {
                ceo3: "null",
                marketer3: "null",
                marketer2: "null",
                marketer1: "null",
                designer2: "null",
                designer1: "null",
                developer2: "null",
            },
            complexity: {
                num: 7,
                text: "Гипер сложная",
            },
            reward: {
                type: "capitilize",
                amount: 2500000,
            },
            id: 25,
            active: false,
        },
        task27: {
            code_name: "task27",
            stage: "stage5",
            name: 'Техническая поддержка',
            type: 'minor',
            desc: 'Описание задания 27',
            time: 3,
            progress: 0,
            additional_expenses: 100000,
            is_performed: true,
            required_roles: [
                "developer2",
                "developer1",
            ],
            assigned_employees: {
                developer2: "null",
                developer1: "null",
            },
            complexity: {
                num: 6,
                text: "Сложная",
            },
            reward: {
                type: "capitilize",
                amount: 1000000,
            },
            id: 26,
            active: false,
        },
    },
})

export default function() {
    return {
        task_list
    }
}